---
title: "542Regression2"
author: "Group 4"
data: "3/8/2021"
output: word_document
---

This is a document for our second hypothesis

```{r}
# import our merged data by using the raw link and named it merge

link="https://raw.githubusercontent.com/Public-Policy-COVID/students_merge/main/Merged_data.csv"
fromPy=read.csv(link, header = T)
row.names(fromPy)=NULL
```

```{r}
# verifying data structure

str(fromPy,width = 50,strict.width='cut')
```

```{r}
# covert integer variables to numeric

fromPy$Deaths_COVID <- as.numeric(fromPy$Deaths_COVID) 
fromPy$Deaths_total <- as.numeric(fromPy$Deaths_total)
str(fromPy,width = 50,strict.width='cut')
```

```{r}
# summary data
summary(fromPy)
```

```{r}
# state the hypothesis#, and name it hypo2
# hypo2 = hypothesis 2: state with higher Deaths_COVID number has more Number_of_beds in hospitals

hypo2=formula(Number_of_beds~ Deaths_COVID+total_population+black_total_pct+aian_total_pct+asian_total_pct+nhopi_total_pct+multiracial_total_pct)
```

```{r}
# compute regression models

gauss2=glm(hypo2,
           data = fromPy,
           family = 'gaussian')
```

```{r}
# check the result of our regression

summary(gauss2)
```

```{r}
# get R square of this regression

library(rsq)
rsq(gauss2, adj = T)
```

```{r}
# to summary plots
library(dotwhisker)
dwplot(gauss2,by_2sd = F)
```

```{r}
# check the margins

library(margins)

cplot(gauss2,'Deaths_COVID')
```

```{r}
cplot(gauss2,'total_population')
```

```{r}
cplot(gauss2,'black_total_pct')
```

```{r}
cplot(gauss2,'aian_total_pct')
```

```{r}
cplot(gauss2,'asian_total_pct')
```

```{r}
cplot(gauss2,'nhopi_total_pct')
```

```{r}
cplot(gauss2,'multiracial_total_pct')
```

```{r}
# plot the interaction

persp(gauss2)
```

